### PR TITLE
Update formulas

### PR DESCRIPTION
**Pull request by awvwgk**
- dftd4: 3.4.0 -> 3.5.0
- s-dftd3: 0.6.0 -> 0.7.0
- tblite: 0.3.0 (new)
- toml-f: 0.2.2 -> 0.3.1
- xtb: 6.5.1 -> 6.6.0
- mctc-lib: 0.3.0 -> 0.3.1

### CODE REVIEW

**Comment by awvwgk** [comment]
Giving up on this on.

**Comment by MtoLStoN** [comment]
I am picking this up, as this seems like a great start.

**Comment by awvwgk** [comment]
I would make a revision bump for gcp and crest such that they use GCC 12 instead

**Comment by MtoLStoN** [comment]
Yeah, that seems like the way smarter way to do this. Thanks!

**Pull request closed without merging**
